name: movie-recommender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - numpy=1.23.5
  - pandas=1.5.2
  - scikit-learn=1.2.0
  - matplotlib=3.6.2
  - seaborn=0.12.1
  - jupyter=1.0.0
  - notebook=6.5.2
  - pytest=7.2.0
  - flake8=6.0.0
  - black=22.12.0
  - isort=5.11.4
  - pip:
      - dvc==2.38.1
      - dvc-gdrive==2.19.1
      - skfuzzy==0.4.2
      - tensorflow==2.11.0
      - keras==2.11.0
      - pyyaml==6.0
      - joblib==1.2.0
      - tqdm==4.64.1
      - mlflow==2.1.1
      - pytest-cov==4.0.0